# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QImage, QPixmap, qRgb
from MyGraphView import QtImageViewer
import numpy as np
import  cv2
from cv2 import  StereoSGBM_create


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1131, 663)
        self.graphicsView = QtImageViewer(Form)
        self.graphicsView.loadImageFromFile()
        self.graphicsView.setGeometry(QtCore.QRect(560, 0, 571, 611))
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(240, 0, 221, 611))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.MinDis = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.MinDis.setStyleSheet("asdas")
        self.MinDis.setMinimum(-10)
        self.MinDis.setPageStep(1)
        self.MinDis.setMaximum(20)
        self.MinDis.setSingleStep(1)
        self.MinDis.setTracking(False)
        self.MinDis.setOrientation(QtCore.Qt.Horizontal)
        self.MinDis.setInvertedAppearance(False)
        self.MinDis.setInvertedControls(False)
        self.MinDis.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.MinDis.setTickInterval(1)
        self.MinDis.setObjectName("MinDis")
        self.verticalLayout.addWidget(self.MinDis)
        self.Maxdis = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.Maxdis.setMinimum(0)
        self.Maxdis.setMaximum(100)
        self.Maxdis.setOrientation(QtCore.Qt.Horizontal)
        self.Maxdis.setObjectName("Maxdis")
        self.verticalLayout.addWidget(self.Maxdis)
        self.blockSize = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.blockSize.setMinimum(1)
        self.blockSize.setMaximum(20)
        self.blockSize.setSingleStep(2)
        self.blockSize.setPageStep(2)
        self.blockSize.setValue(1)

        self.blockSize.setOrientation(QtCore.Qt.Horizontal)
        self.blockSize.setObjectName("blockSize")
        self.verticalLayout.addWidget(self.blockSize)
        self.P1 = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.P1.setOrientation(QtCore.Qt.Horizontal)
        self.P1.setObjectName("P1")
        self.P1.setMaximum(5000)
        self.verticalLayout.addWidget(self.P1)
        self.P2 = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.P2.setOrientation(QtCore.Qt.Horizontal)
        self.P2.setObjectName("P2")
        self.P2.setMaximum(10000)

        self.verticalLayout.addWidget(self.P2)
        self.disp12MaxDiff = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.disp12MaxDiff.setOrientation(QtCore.Qt.Horizontal)
        self.disp12MaxDiff.setObjectName("disp12MaxDiff")
        self.disp12MaxDiff.setPageStep(1)
        self.verticalLayout.addWidget(self.disp12MaxDiff)
        self.uniquenessRatio = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.uniquenessRatio.setMinimum(1)
        self.uniquenessRatio.setValue(1)
        self.uniquenessRatio.setMaximum(25)
        self.uniquenessRatio.setOrientation(QtCore.Qt.Horizontal)
        self.uniquenessRatio.setObjectName("uniquenessRatio")
        self.verticalLayout.addWidget(self.uniquenessRatio)
        self.speckleWindowSize = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.speckleWindowSize.setMinimum(0)
        self.speckleWindowSize.setMaximum(400)
        self.speckleWindowSize.setPageStep(1)
        self.speckleWindowSize.setValue(1)
        self.speckleWindowSize.setOrientation(QtCore.Qt.Horizontal)
        self.speckleWindowSize.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.speckleWindowSize.setPageStep(1)
        self.speckleWindowSize.setTickInterval(1)
        self.speckleWindowSize.setObjectName("speckleWindowSize")
        self.verticalLayout.addWidget(self.speckleWindowSize)
        self.speckleRange = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.speckleRange.setMaximum(5)
        self.speckleRange.setOrientation(QtCore.Qt.Horizontal)
        self.speckleRange.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.speckleRange.setTickInterval(1)
        self.speckleRange.setObjectName("speckleRange")
        self.verticalLayout.addWidget(self.speckleRange)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(80, 30, 134, 32))
        self.label_3.setStyleSheet("font: 18pt \"Segoe UI Historic\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(60, 90, 151, 32))
        self.label_4.setStyleSheet("font: 18pt \"Segoe UI Historic\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(110, 160, 101, 32))
        self.label_5.setStyleSheet("font: 18pt \"Segoe UI Historic\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(180, 220, 31, 32))
        self.label_6.setStyleSheet("font: 18pt \"Segoe UI Historic\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(180, 290, 31, 32))
        self.label_7.setStyleSheet("font: 18pt \"Segoe UI Historic\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(30, 410, 181, 32))
        self.label_8.setStyleSheet("font: 18pt \"Segoe UI Historic\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(50, 350, 161, 32))
        self.label_9.setStyleSheet("font: 18pt \"Segoe UI Historic\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(-10, 480, 211, 32))
        self.label_10.setStyleSheet("font: 18pt \"Segoe UI Historic\";")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(50, 540, 151, 32))
        self.label_11.setStyleSheet("font: 18pt \"Segoe UI Historic\";")
        self.label_11.setObjectName("label_11")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(470, 30, 71, 31))
        self.label_2.setStyleSheet("font: 18pt \"Arial Rounded MT Bold\";")
        self.label_2.setObjectName("label_2")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(470, 90, 71, 31))
        self.label_12.setStyleSheet("font: 18pt \"Arial Rounded MT Bold\";")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(470, 160, 71, 31))
        self.label_13.setStyleSheet("font: 18pt \"Arial Rounded MT Bold\";")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(470, 220, 71, 31))
        self.label_14.setStyleSheet("font: 18pt \"Arial Rounded MT Bold\";")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(470, 280, 71, 31))
        self.label_15.setStyleSheet("font: 18pt \"Arial Rounded MT Bold\";")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(470, 350, 71, 31))
        self.label_16.setStyleSheet("font: 18pt \"Arial Rounded MT Bold\";")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(470, 410, 71, 31))
        self.label_17.setStyleSheet("font: 18pt \"Arial Rounded MT Bold\";")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(470, 480, 71, 31))
        self.label_18.setStyleSheet("font: 18pt \"Arial Rounded MT Bold\";")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(470, 550, 71, 31))
        self.label_19.setStyleSheet("font: 18pt \"Arial Rounded MT Bold\";")
        self.label_19.setObjectName("label_19")
        self.stereoComputer=None
        self.leftImg, self.rightImg = None,None
        self.retranslateUi(Form)
        self.MinDis.valueChanged['int'].connect(self.label_2.setNum)
        self.MinDis.valueChanged['int'].connect(self.update_stereoComputer)

        self.Maxdis.valueChanged['int'].connect(self.label_12.setNum)
        self.Maxdis.valueChanged['int'].connect(self.update_stereoComputer)

        self.blockSize.valueChanged['int'].connect(self.label_13.setNum)
        self.blockSize.valueChanged['int'].connect(self.update_stereoComputer)


        self.P1.valueChanged['int'].connect(self.label_14.setNum)
        self.P1.valueChanged['int'].connect(self.update_stereoComputer)

        self.P2.valueChanged['int'].connect(self.label_15.setNum)
        self.P2.valueChanged['int'].connect(self.update_stereoComputer)

        self.disp12MaxDiff.valueChanged['int'].connect(self.label_16.setNum)
        self.disp12MaxDiff.valueChanged['int'].connect(self.update_stereoComputer)

        self.uniquenessRatio.valueChanged['int'].connect(self.label_17.setNum)
        self.uniquenessRatio.valueChanged['int'].connect(self.update_stereoComputer)

        self.speckleWindowSize.valueChanged['int'].connect(self.label_18.setNum)
        self.speckleWindowSize.valueChanged['int'].connect(self.update_stereoComputer)

        self.speckleRange.valueChanged['int'].connect(self.label_19.setNum)
        self.speckleRange.valueChanged['int'].connect(self.update_stereoComputer)


        self.setupComponent()

        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.speckleRange.setWhatsThis(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; vertical-align:sub;\">asdasdad</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "minDisparity"))
        self.label_4.setText(_translate("Form", "Max Disparitiy"))
        self.label_5.setText(_translate("Form", "blockSize"))
        self.label_6.setText(_translate("Form", "P1"))
        self.label_7.setText(_translate("Form", "P2"))
        self.label_8.setText(_translate("Form", "uniquenessRatio"))
        self.label_9.setText(_translate("Form", "disp12MaxDiff"))
        self.label_10.setText(_translate("Form", "speckleWindowSize    "))
        self.label_11.setText(_translate("Form", "speckleRange"))
        self.label_2.setText(_translate("Form", "2"))
        self.label_12.setText(_translate("Form", "2"))
        self.label_13.setText(_translate("Form", "2"))
        self.label_14.setText(_translate("Form", "2"))
        self.label_15.setText(_translate("Form", "2"))
        self.label_16.setText(_translate("Form", "2"))
        self.label_17.setText(_translate("Form", "2"))
        self.label_18.setText(_translate("Form", "2"))
        self.label_19.setText(_translate("Form", "2"))

    def setupComponent(self):
        stereoComputer = StereoSGBM_create(minDisparity=0,
                                                numDisparities=16,
                                                blockSize=1,
                                                uniquenessRatio=1,
                                                speckleWindowSize=150,
                                                speckleRange=1,
                                                disp12MaxDiff=10,
                                                mode=cv2.StereoSGBM_MODE_HH,
                                                P1=5 * 3 * 1 ** 2,  # 8*3*win_size**2,
                                                P2=10 * 3 * 1 ** 2)  # 32*3*win_size**2
        leftImg, rightImg = self.graphicsView.getImages()
        disp_map = stereoComputer.compute(leftImg, rightImg).astype(np.uint8)
        h, w = disp_map.shape
        new = disp_map.copy()
        image = self.numpyQImage(new)
        pixmap = QPixmap.fromImage(image)

        self.graphicsView.resize(h, w)
        self.graphicsView.setImage(pixmap)
    def compute_disp_and_show(self,stereoComputer):
        leftImg, rightImg = self.graphicsView.getImages()
        stereoComputer = StereoSGBM_create(minDisparity=self.MinDis.value(),
                                           numDisparities=self.Maxdis.value() - self.Maxdis.value(),
                                           blockSize=1,
                                           uniquenessRatio=1,
                                           speckleWindowSize=150,
                                           speckleRange=1,
                                           disp12MaxDiff=10,
                                           mode=cv2.StereoSGBM_MODE_HH,
                                           P1=5 * 3 * 1 ** 2,  # 8*3*win_size**2,
                                           P2=10 * 3 * 1 ** 2)  # 32*3*win_size**2
        disp_map = stereoComputer.compute(leftImg, rightImg).astype(np.uint8)
        h, w = disp_map.shape
        new = disp_map.copy()
        image = self.numpyQImage(new)
        pixmap = QPixmap.fromImage(image)
        self.graphicsView.resize(h, w)
        self.graphicsView.setImage(pixmap)

    def update_stereoComputer(self):
        self.win_size = 1
        numDisparities = abs(self.Maxdis.value()-self.MinDis.value())
        numDisparities =  16 * (round(float(numDisparities) / 16)+1)
        # self.P1.setValue(8*3*self.blockSize.value()**2)
        # self.P2.setValue(32*3*self.blockSize.value()**2)  #this two value are  recommand as website of  https://docs.opencv.org/3.4/d2/d85/classcv_1_1StereoSGBM.html

        stereoComputer = StereoSGBM_create(minDisparity=self.MinDis.value(),
                                                numDisparities=numDisparities,
                                                blockSize=int(self.blockSize.value()),
                                                uniquenessRatio=int(self.uniquenessRatio.value()),
                                                speckleWindowSize=int(self.speckleWindowSize.value()),
                                                speckleRange=int(self.speckleRange.value()),
                                                disp12MaxDiff=int(self.disp12MaxDiff.value()),
                                                mode=cv2.StereoSGBM_MODE_HH,
                                                P1=int(self.P1.value()),  # 8*3*win_size**2,
                                                P2=int(self.P2.value()))  # 32*3*win_size**2
        print(self.MinDis.value(),numDisparities,int(self.blockSize.value()),
              int(self.uniquenessRatio.value()),int(self.speckleWindowSize.value()),
              int(self.speckleRange.value()),int(self.disp12MaxDiff.value()),
              int(self.P1.value()), )

        leftImg, rightImg = self.graphicsView.getImages()
        l,r = leftImg.copy(),rightImg.copy()
        disp_map = stereoComputer.compute(l, r).astype(np.uint8)
        h, w = disp_map.shape
        new = disp_map.copy()
        image = self.numpyQImage(new)
        pixmap = QPixmap.fromImage(image)

        self.graphicsView.resize(h, w)
        self.graphicsView.setImage(pixmap)

    def numpyQImage(self, image):
        qImg = QImage()
        if image.dtype == np.uint8:
            if len(image.shape) == 2:
                channels = 1
                height, width = image.shape
                bytesPerLine = channels * width
                qImg = QImage(
                    image.data, width, height, bytesPerLine, QImage.Format_Indexed8
                )
                qImg.setColorTable([qRgb(i, i, i) for i in range(256)])
            elif len(image.shape) == 3:
                if image.shape[2] == 3:
                    height, width, channels = image.shape
                    bytesPerLine = channels * width
                    qImg = QImage(
                        image.data, width, height, bytesPerLine, QImage.Format_RGB888
                    )
                elif image.shape[2] == 4:
                    height, width, channels = image.shape
                    bytesPerLine = channels * width
                    fmt = QImage.Format_ARGB32
                    qImg = QImage(
                        image.data, width, height, bytesPerLine, QImage.Format_ARGB32
                    )
        return qImg
